---
title: "终结任务—Java并发系列之四"
date: 2020-10-23
lastmod: 2020-10-23
draft: false
tags: [Java进阶]
categories: [Java]
author: "wangy325"

hasJCKLanguage: true

weight: 10
mathjax: true
autoCollapseToc: false
---

一般地，如果程序运行良好，任务执行完所需操作后自然结束，任务终结

如果任务执行时出现异常，任务也会终结

在设计多个线程协同工作的任务时，需要判断任务终结的条件，以便合适地终结任务，这点尤为重要

在本节中主要讨论在多线程协同工作的情况下，如何合适的终结任务

<!--more-->

# 响应中断

在讨论[Object超类](/endlessriver/post/tech/advance_java/资源访问受限/#8-再论object超类)的时候，我们曾通过“录音-播放”模型简单阐述线程之间的协同工作，在那个示例中，方便起见，我们通过`System.exit(0);`来粗暴地结束程序的运行。这种方式在并发编程实践中是不被允许的

接下来的示例中，我们再次以线程之间的协同工作为切点，讨论如何“合理地”终结任务的运行

下例模拟汽车的“打蜡-抛光”过程，抛光必须在打蜡完成之后，同样的，打蜡之前汽车必须是抛光过的

```java
public class Wax {

    static class Car {
        private boolean waxOn = false;

        public synchronized void waxed() {
            waxOn = true; // Ready to buff
            notifyAll();
        }

        public synchronized void buffed() {
            waxOn = false; // Ready for another coat of wax
            notifyAll();
        }

        public synchronized void waitForWaxing()
            throws InterruptedException {
            // waxOn = false时一直等待
            while (!waxOn)
                wait();
        }

        public synchronized void waitForBuffing()
            throws InterruptedException {
            // waxOn = true时一直等待
            while (waxOn)
                wait();
        }
    }

    static class WaxOn implements Runnable {
        private Car car;

        public WaxOn(Car c) {
            car = c;
        }

        @Override
        public void run() {
            try {
                while (!Thread.interrupted()) {
                    TimeUnit.MILLISECONDS.sleep(100);
                    System.out.print("Wax On! ");
                    car.waxed();
                    car.waitForBuffing();
                }
            } catch (InterruptedException e) {
                System.out.println("WaxOn Exiting via interrupt");
            }
            System.out.println("Ending Wax On task");
        }
    }

    static class BufferOn implements Runnable {
        private Car car;

        public BufferOn(Car c) {
            car = c;
        }

        @Override
        public void run() {
            try {
                while (!Thread.interrupted()) {
                    // 任务直接进入等待直到被唤醒, waxOn = true时得以执行
                    car.waitForWaxing();
                    System.out.print("Wax Off! ");
                    TimeUnit.MILLISECONDS.sleep(100);
                    car.buffed();
                }
            } catch (InterruptedException e) {
                System.out.println("BufferOn Exiting via interrupt");
            }
            System.out.println("Ending Buffer On task");
        }
    }

    public static void main(String[] args) throws Exception {
        Car car = new Car();
        ExecutorService exec = Executors.newCachedThreadPool();
        exec.execute(new BufferOn(car));
        exec.execute(new WaxOn(car));
        TimeUnit.SECONDS.sleep(2); // Run for a while...
        exec.shutdownNow(); // Interrupt all tasks
    }
}
/* Output: (95% match)
Wax On! Wax Off! Wax On! Wax Off! Wax On! Wax Off! Wax On! Wax Off! Wax On! Wax Off! Wax On! Wax Off! Wax On! Wax Off! Wax On! Wax Off! Wax On! Wax Off! Wax On! Wax Off! BufferOn Exiting via interrupt
WaxOn Exiting via interrupt
Ending Wax On task
Ending Buffer On task
*///:~
```

因为两个任务是交互等待-执行的，调用`wait()`方法而进入**WAITING**状态的线程可以被中断并抛出异常[^1]，上面的输出显示`BufferOn`任务先响应中断，这只是可能的情况之一，因为输出 *Wax Off!* 之后`BufferOn`任务会进入等待，而正好被中断

调用执行器的`shutdownNow()`方法关闭提交的任务，`shutdownNow()`方法会立即给已经提交的任务发送一个中断`interrupt()`命令。调用`shutdownNow()`之后，可以看到两个任务都抛出`InterruptedException`

> ⚠️注意： 两个任务都抛出中断异常和任务中的sleep方法有关，由于sleep和wait都可以被中断并抛出异常，所以异常的抛出是由谁引发的并不容易确定。虽然try块位于任务的最外层，但是`Thread.interrupted()`方法并不抛出异常

上例实际上是利用了中断线程而出现的异常而终止线程的运行，然而，**BLOCKED**[^2]状态下的线程无法响应中断

# 无法中断

Thread提供了`interrupt()`方法，用于设置线程的中断状态。为了调用此方法，你必须持有Thread对象。并发编程过程中一般避免显式创建线程，上例中使用了`shutdownNow()`向任务发送`interrup()`命令，同样地，Java提供一个带有类型参数的接口[Future\<V\>](/endlessriver/post/tech/advance_java/获取任务的返回值/#future-接口)，它具有取消任务的能力

但是，阻塞状态下的线程是否都能响应中断呢？

```Java
public class Interrupting {
    private static ExecutorService exec = Executors.newCachedThreadPool();

    static void test(Runnable r) throws InterruptedException {
        // 构造一个可中断的任务
        Future<?> f = exec.submit(r);
        TimeUnit.MILLISECONDS.sleep(100);
        // 中断任务
        System.out.println(r.getClass().getSimpleName() + " Interrupt: " + f.cancel(true));
    }

    public static void main(String[] args) throws Exception {
        test(new SleepBlocked());
        test(new IOBlocked(System.in)); // 不能中断
        test(new SynchronizedBlocked()); // 不能中断
        TimeUnit.SECONDS.sleep(3);
        System.exit(0); // ... since last 2 interrupts failed
    }

    /** sleep可以被中断 */
    static class SleepBlocked implements Runnable {
        @Override
        public void run() {
            try {
                TimeUnit.SECONDS.sleep(100);
            } catch (InterruptedException e) {
                System.out.println("InterruptedException");
            }
            System.out.println("Exiting SleepBlocked.run()");
        }
    }

    /** I/O不可被中断 */
    static class IOBlocked implements Runnable {
        private InputStream in;

        public IOBlocked(InputStream is) {
            in = is;
        }

        @Override
        public void run() {
            try {
                System.out.println("Waiting for read():");
                in.read();
            } catch (Exception e) {
                if (Thread.currentThread().isInterrupted()) {
                    System.out.println("Interrupted from blocked I/O");
                } else {
                    throw new RuntimeException(e);
                }
            }
            System.out.println("Exiting IOBlocked.run()");
        }
    }

    /** 不可被中断 */
    static class SynchronizedBlocked implements Runnable {
        public synchronized void f() {
            while (true) // Never releases lock
                Thread.yield();
        }

        public SynchronizedBlocked() {
            // 构造之后就获取锁而不释放
            new Thread(() -> {
                f(); // Lock acquired by this thread
            }).start();
        }

        /** run()方法将一直阻塞 */
        @Override
        public void run() {
            System.out.println("Trying to call f()");
            f();
            System.out.println("Exiting SynchronizedBlocked.run()");
        }
    }
}
/* output:
InterruptedException
SleepBlocked Interrupt: true
Exiting SleepBlocked.run()
Waiting for read():
IOBlocked Interrupt: true
Trying to call f()
SynchronizedBlocked Interrupt: true
 *///:~
```

由于Future的`cancel(boolean)`方法也是向执行任务的线程发送`interrupt()`命令，上例中3个任务，只有`SleepBlocked`在休眠时被中断并退出运行，其他的两个任务`IOBlocked`和`SynchronizedBlocked`均没有被中断。实际上，在编码过程中我们也可以发现，只有`sleep()`方法需要处理`InterruptedException`异常，而无论时I/O还是尝试调用synchronized方法，都不需要处理`InterruptedException`

对于I/O阻塞的情况，有一个简单的处理办法——即关闭任务在其上发生阻塞的资源

```java
public class CloseResource {
    public static void main(String[] args) throws Exception {
        ExecutorService exec = Executors.newCachedThreadPool();
        InputStream socketInput = new Socket("localhost", 8080).getInputStream();
        exec.execute(new Interrupting.IOBlocked(socketInput));
        exec.execute(new Interrupting.IOBlocked(System.in));
        TimeUnit.MILLISECONDS.sleep(10);
        System.out.println("Shutting down all threads");
        // 两个任务都无法响应中断
        exec.shutdownNow();
        TimeUnit.SECONDS.sleep(1);
        System.out.println("Closing " + socketInput.getClass().getName());
        // 关闭资源可以使线程响应中断
        socketInput.close(); // Releases blocked thread
        TimeUnit.SECONDS.sleep(1);
        System.out.println("Closing " + System.in.getClass().getName());
        System.in.close(); // Releases blocked thread
    }
}
/* Output: (85% match)
Waiting for read():
Waiting for read():
Shutting down all threads
Closing java.net.SocketInputStream
Interrupted from blocked I/O
Exiting IOBlocked.run()
Closing java.io.BufferedInputStream
Exiting IOBlocked.run()
*///:~
```

上例中的2个任务都无法响应中断，但是一旦关闭资源，那么阻塞就被中断

对于因获取锁失败而阻塞的情况，实际上，上例中的情况可以看作是**死锁**，由于任务无法获取对象的锁而一直阻塞。幸运的是，Java提供ReentrantLock锁，其具备在因获取锁而阻塞但是又能响应中断的能力

```Java
public class LockingInterrupt {

    // 可重入锁获取锁的时候可以被中断
    private Lock lock = new ReentrantLock();

    public LockingInterrupt() {
        // lock the instance once constructed
        lock.lock();
    }

    void f() {
        try {
            // invoke can be interrupted
            lock.lockInterruptibly();
            System.out.println("acquire lock in f() success");
        }catch (InterruptedException e){
            System.out.println("Interrupted from acquire lock in f()");
        }
    }

    static class MutexTask implements Runnable{
        LockingInterrupt mbi = new LockingInterrupt();
        @Override
        public void run() {
            System.out.println("waiting for f()");
            mbi.f();
            System.out.println("Broken out of blocked call");
        }
    }

    public static void main(String[] args) throws InterruptedException {
        Thread t = new Thread(new MutexTask());
        t.start();
        // 中断t，若不中断，t会一直阻塞
        t.interrupt();
    }
}
/*
waiting for f()
Interrupted from acquire lock in f()
Broken out of blocked call
*///:~
```

上例中，`LockingInterrupt`初始化的时候就占用锁，并没有释放锁，而在运行`f()`方法的时候再去获取锁时任务就被阻塞了，在调用`interrupt()`方法中断的时候，`lockInterruptibly()`响应了中断，任务结束程序退出

# 惯用法

从上面的例子我们已经知道，可以通过检查线程的中断状态来结束任务的执行。下面的例子展示了一种惯用法，它使用try-finally块来紧跟资源，以应对任何时候任务出现中断时保证资源被释放

```Java
public class InterruptingIdiom {

    /** 需要清理的资源类 */
    static class NeedsCleanup {
        private final int id;

        public NeedsCleanup(int ident) {
            id = ident;
            System.out.println("NeedsCleanup " + id);
        }

        public void cleanup() {
            System.out.println("Cleaning up " + id);
        }
    }

    static class Blocked3 implements Runnable {
        private volatile double d = 0.0;

        @Override
        public void run() {
            try {
                while (!Thread.interrupted()) {
                    NeedsCleanup n1 = new NeedsCleanup(1);
                    // 在n1之后紧跟try-finally块，保证资源被合理的清除
                    // node 1
                    try {
                        System.out.println("Sleeping");
                        TimeUnit.SECONDS.sleep(1);
                        NeedsCleanup n2 = new NeedsCleanup(2);
                        // 同理
                        // node2
                        try {
                            System.out.println("Calculating");
                            //耗时操作
                            for (int i = 1; i < 2500000; i++) {
                                d = d + (Math.PI + Math.E) / d;
                            }
                            // node3
                            System.out.println("Finished time-consuming operation");
                        } finally {
                            n2.cleanup();
                        }
                    } finally {
                        n1.cleanup();
                    }
                }
                System.out.println("Exiting via while() test");
            } catch (InterruptedException e) {
                System.out.println("Exiting via InterruptedException");
            }
        }
    }

    public static void main(String[] args) throws Exception {
        if (args.length != 1) {
            System.out.println("usage: java InterruptingIdiom delay-in-mS");
            System.exit(1);
        }
        Thread t = new Thread(new Blocked3());
        t.start();
        TimeUnit.MILLISECONDS.sleep(new Integer(args[0]));
        t.interrupt();
    }
}
/* Output: (Sample)
NeedsCleanup 1
Sleeping
NeedsCleanup 2
Calculating
Finished time-consuming operation
Cleaning up 2
Cleaning up 1
NeedsCleanup 1
Sleeping
Cleaning up 1
Exiting via InterruptedException
*///:~
```

上例接收一个参数，表示程序中断之前的运行时间(ms)，由于任务中有一段耗时的循环操作，当参数大小不同时，程序的输出会有所差异

任务可能在node1和node2之间中断，因此其输出为：

    NeedsCleanup 1
    Sleeping
    Cleaning up 1
    Exiting via InterruptedException

当任务在node2和node3之间设置中断状态，再次进入循环时中断被监测到，程序退出，此时的输出为：

    NeedsCleanup 1
    Sleeping
    NeedsCleanup 2
    Calculating
    Finished time-consuming operation
    Cleaning up 2
    Cleaning up 1
    Exiting via while() test

总之，无论任务在何时被释放，其创建的资源都会被合适地释放


[^1]: TIJ第四版第21章并发（694页）在描述线程的状态时，将调用休眠/等待之后线程的状态称为阻塞。为避免混淆，本文采用[Thread.State](https://docs.oracle.com/javase/7/docs/api/java/lang/Thread.State.html)中关于线程的描述，并认为其不应该被称为阻塞状态

[^2]: 本博客约定此状态（等待锁）的线程才处于阻塞状态
